inject_layers = ["com.illusivesoulworks.colytra.client.ColytraLayer", "com.illusivesoulworks.elytraslot.client.ElytraSlotLayer", "com.kyanite.deeperdarker.client.render.SoulElytraRenderer", "pw.lakuna.elytra_trinket.ElytraTrinketFeatureRenderer", "org.betterx.betterend.client.render.ArmoredElytraLayer"]
enabled = true
adaptive_gravity = true
prevent_snapping = true
gravity_multiplier = 1.0
elytra_lean_multiplier = 1.0
elytra_pan_multiplier = 1.0
elytra_roll_multiplier = 1.0
elytra_spread_multiplier = 1.0
decline_multiplier = 1.0
