#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Jul 15 20:18:39 CST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=3
shaderPack=BSL_v10.0 + Clrwl_1.0.2.zip
