version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 4.0
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
offroad = true
kaleidoscope_cookery = true
kaleidoscope_end = true
sourceblock = true
createprism = true
drivebywire = true
kaleidoscope_tavern = true
vista = true
create = true
aeronautics = true
netmusic = true
create_aeronautics_toolgun = true
simulated = true
copycats = true
create_extra_casing = true
minecraft = true
create_dragons_plus = true
create_connected = true
createdieselgenerators = true
create_enchantment_industry = true
fluidlogistics = true
create_jetpack = true
aeronautics_utility_objects = true
create_things_and_misc = true
createaddition = true
railways = true
createbuttercat = true
create_mobile_packages = true
tacz = true
moonlight = true
infinite_light = true
chickenchunks = true
aeroworks = true
exposure = true
create_integrated_farming = true
